version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: sofpos_postgres
    restart: always
    environment:
      POSTGRES_DB: sofpos
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sofpos_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sofpos_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sofpos_network

  app:
    build: .
    container_name: sofpos_app
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/sofpos
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - sofpos_network

volumes:
  postgres_data:

networks:
  sofpos_network: